[package]
name = "CPlusPlus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "dfs"
path = "graph/dfs/main.rs"

[dependencies]
